# Generated by Django 2.2.2 on 2019-07-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
